/**
 * Library output generation.
 *
 * Generates the library.json and library.ts files from analyzed metadata.
 *
 * @see library_generate.ts for the main generation entry point
 * @see library_pipeline.ts for pipeline orchestration functions
 * @see library_gen.ts for Gro-specific integration
 *
 * @module
 */

import type {PackageJson} from '@fuzdev/fuz_util/package_json.js';
import type {SourceJson} from '@fuzdev/fuz_util/source_json.js';
import {library_json_parse, type LibraryJson} from '@fuzdev/fuz_util/library_json.js';

/**
 * Result of generating library output files.
 * Contains both the JSON data and the TypeScript wrapper file.
 */
export interface LibraryOutputResult {
	/** JSON content for library.json */
	json_content: string;
	/** TypeScript wrapper content for library.ts */
	ts_content: string;
}

/**
 * Generate the library.json and library.ts file contents.
 * Parses at generation time so runtime only needs the pre-computed result.
 *
 * Returns JSON + .ts wrapper because:
 * - JSON is natively importable by Node.js and Vite without TypeScript loaders
 * - Works in CI environments that don't have TS compilation
 * - The .ts wrapper validates with zod and exports with proper types
 *   (JSON imports get widened types like `string` instead of literal unions)
 */
export const library_generate_output = (
	package_json: PackageJson,
	source_json: SourceJson,
): LibraryOutputResult => {
	const is_this_fuz_util = package_json.name === '@fuzdev/fuz_util';
	const fuz_util_prefix = is_this_fuz_util ? './' : '@fuzdev/fuz_util/';

	// Parse at generation time, not runtime
	const library_json: LibraryJson = library_json_parse(package_json, source_json);

	const json_content = JSON.stringify(library_json, null, '\t') + '\n';

	const banner = '// generated by library.gen.ts - do not edit';

	const ts_content = `${banner}

import type {LibraryJson} from '${fuz_util_prefix}library_json.js';

import json from './library.json' with {type: 'json'};

export const library_json: LibraryJson = json as LibraryJson;

${banner}
`;

	return {json_content, ts_content};
};
