import { existsSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { TaskError, type Task } from '@fuzdev/gro';
import { spawn_out } from '@fuzdev/fuz_util/process.ts';

import { project_items } from './projects.ts';
import { daily_counts_from_timestamps, type ProjectStatsSnapshot } from './project_stats.ts';

export const PROJECT_STATS_DATA_PATH = 'src/lib/project_stats_data.ts';

export const task: Task = {
	summary: 'update project_stats_data.ts from the git histories of sibling project repos',
	run: async ({ log, invoke_task }) => {
		const now = new Date();
		const end_date = now.toISOString().slice(0, 10);
		const projects: ProjectStatsSnapshot['projects'] = [];
		for (const { name } of project_items) {
			const dir = resolve('..', name);
			if (!existsSync(join(dir, '.git'))) {
				throw new TaskError(`Missing sibling repo for project "${name}" at ${dir}`);
			}
			// TODO extract a `git_commit_timestamps` helper to fuz_util's `git.ts` cluster
			const { stdout } = await spawn_out('git', ['log', '--pretty=%ct'], { cwd: dir });
			const timestamps = stdout
				?.trim()
				.split('\n')
				.map((line) => Number(line));
			if (!timestamps?.length || timestamps.some((t) => !Number.isFinite(t))) {
				throw new TaskError(`Failed to read commit timestamps for project "${name}" at ${dir}`);
			}
			const bucketed = daily_counts_from_timestamps(timestamps, end_date);
			if (!bucketed) {
				throw new TaskError(`No commits found for project "${name}" at ${dir}`);
			}
			projects.push({ name, ...bucketed });
			log.info(`collected ${timestamps.length} commits from ${name} since ${bucketed.start_date}`);
		}
		const snapshot: ProjectStatsSnapshot = {
			generated_at: now.toISOString(),
			end_date,
			projects
		};
		const content = `// generated by src/lib/project_stats_update.task.ts — do not edit directly, run \`gro project_stats_update\`

import type { ProjectStatsSnapshot } from './project_stats.ts';

export const project_stats_data: ProjectStatsSnapshot = ${JSON.stringify(snapshot)};
`;
		writeFileSync(PROJECT_STATS_DATA_PATH, content);
		await invoke_task('format', { _: [PROJECT_STATS_DATA_PATH] });
		log.info(`wrote ${PROJECT_STATS_DATA_PATH}`);
	}
};
