// generated by library.gen.json.ts - do not edit

import _json from './library.json' with {type: 'json'};
import {SourceJson} from '@fuzdev/fuz_util/source_json.js';
import {library_json_parse} from '@fuzdev/fuz_util/library_json.js';

// Validate source_json with zod to get proper types (JSON imports widen literals to string)
const source_json = SourceJson.parse(_json.source_json);

export const library_json = library_json_parse(_json.package_json, source_json);
